name: Deploy to gh-pages!
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Clean install dependencies
        run: npm install
        
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
